name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun v1.2
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.23

      - name: Install dependencies
        run: npm ci

      - name: Install sharp
        run: bun install canvas

      - name: Run ESLint
        run: npm run lint

      - name: Create temp JSON files
        run: |
          cp ./config/config-example.json config/config.json 
          cp ./config/snowflakes-commands-example.json config/snowflakes-commands.json 
          cp ./config/siteConfig-example.json config/siteConfig.json 
          cp ./data/banned-example.json data/banned.json 
          exit 0

      - name: Check TypeScript Version
        run: |
          npx tsc --version
          npm ls discord.js
          npm ls @types/node
      
      - name: Run TSCheck
        run: npm run tscheck
